services:
  - type: web
    name: fire-ignition-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run fire_detect_web.py --server.port=10000 --server.address=0.0.0.0