services:
  - type: web
    name: fire-ignition-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run fire_detect_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
